require("./common/module/dotenv")()
const express = require("express")
const app = express()
const path = require("path")
const cors = require("cors")
const notFoundRouter = require("./common/error/not-found-mw")
const errorRouter = require("./common/error/error-mw")
app.listen(process.env.port)
app.set("view engine", "ejs")
app.set("views", path.resolve(__dirname, "./views"))
app.use(cors(require("./common/module/cors")()))
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.use("/", express.static("./public"))
app.use("/upload", express.static("./storages"))

const shopRouter = require("./routes/shop-router")
const bookRouter = require("./routes/book-router")
const publicRouter = require("./routes/public-router")
const { isApi } = require("./middlewares/auth-mw")

app.use("/shop", isApi(), shopRouter)
app.use("/book", bookRouter)
// app.use("/admin", isAdmin(), publicRouter)
app.use("/public", publicRouter)

app.use(notFoundRouter)
app.use(errorRouter)
